%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step XX: ART Batch (calling Conn commands) 
%
% Code generated by Kathleen Hupfeld--Seidler Lab
% Last updated Sept. 2019 
%
% Code edited by Signe Hagner Oct. 2019. Nothing is deleted from the old
% code ? it is just commented.
% Code shared by Boris Kleber
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 

function conn_for_art_bashscript(subjects,varargin) 

%% Loop for subjects
for sbj = 1:size(subjects, 1)
    sub_path = fullfile(subjects(sbj).folder, subjects(sbj).name, 'ses-001', 'derivatives', 'SPM_prepro', 'func');
    
    %Get normalized scans
    nEPI_tydyy = dir (fullfile(sub_path, 'normalize','*task-tydyy*.nii'));
    nEPI_uulaa = dir (fullfile(sub_path, 'normalize','*task-uulaa*.nii'));
    
    for i=1:size(nEPI_tydyy)
        fname_nEPI_tydyy{i,1}=fullfile(sub_path,nEPI_tydyy(i).name);
    end
    
    for j=1:size(nEPI_uulaa)
        fname_nEPI_uulaa{j,1}=fullfile(sub_path,nEPI_uulaa(j).name);
    end
    % Get realignment parameters
    rp_tydyy = dir (fullfile(sub_path,'*task-tydyy*.txt'));
    rp_uulaa = dir (fullfile(sub_path, '*task-uulaa*.txt'));

%------------------------------------------------------------------------------------
% ART batch 
%	-Run on wra* files. 
%	-Not recommended to run on smoothed files (see Conn / ART NITRC post). 
%------------------------------------------------------------------------------------

%Run ART
clear batch 
batch.filename=fullfile(sub_path,'conn_ART.mat');
batch.Setup.isnew=1;
batch.Setup.nsubjects=1;
batch.Setup.nsessions =2;
batch.Setup.l1covariates.names{1}='realignment';
batch.Setup.l1covariates.files{1}{1}{1}=rp_tydyy.name;
batch.Setup.l1covariates.files{1}{1}{2}=rp_uulaa.name;
batch.Setup.functionals{1}{1}=fname_nEPI_tydyy;
batch.Setup.functionals{1}{2}= fname_nEPI_uulaa;
batch.Setup.preprocessing.art_thresholds(1)=4; %art_thresholds(1): threshold value for global-signal (z-value; default 5) 
batch.Setup.preprocessing.art_thresholds(2)=3; %art_thresholds(2): threshold value for subject-motion (mm; default .9) 
batch.Setup.preprocessing.art_thresholds(3)=1; %art_thresholds(3): global-signal threshold based on scan-to-scan changesin global-BOLD measure (default 1)  
batch.Setup.preprocessing.art_thresholds(4)=1; %art_thresholds(4): subject-motion threshold based on scan-to-scan changes in subject-motion measure (default 1) 
batch.Setup.preprocessing.art_thresholds(5)=1; %art_thresholds(5): subject-motion threhsold based on composite-movement measure (default 1) 
batch.Setup.preprocessing.steps={'functional_art'}; 

conn_batch(batch); %run the Conn batch 

end





