%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Step XX: ART Batch (calling Conn commands) 
%
% Code generated by Kathleen Hupfeld--Seidler Lab
% Last updated Sept. 2019 
%
% Code edited by Signe Hagner Oct. 2019. Nothing is deleted from the old
% code ? it is just commented.
%Code shared by Boris
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 

function conn_for_art_bashscript(subject,path,session) 

%------------------------------------------------------------------------------------
% Set the path  
%------------------------------------------------------------------------------------
%data_path = ['E:\_GABA_Aging_Data\',subjID,'\02_MRI\02_Nifti\03_Task_fMRI\']; data_path
 if subject<10
        folder = string(['000' num2str(subject)]);
    else
        folder = string(['00' num2str(subject)]);
 end
 
data_path = dir(char(strcat('/projects/MINDLAB2017_MR-Singing/scratch/data2020_Boris/fMRI/', path, '/', folder, '/*/MR/BOLD',num2str(session),'/NATSPACE/')));
data_path = data_path(1).folder;
data_path;


%------------------------------------------------------------------------------------
% Initialise SPM + Conn 
%------------------------------------------------------------------------------------
spm('Defaults','fMRI'); spm_jobman('initcfg');
%addpath C:\Users\APK-User\Documents\spm12\toolbox\conn
addpath /users/bokle/matlab/conn

%------------------------------------------------------------------------------------
% ART batch 
%	-Run on wra* files. 
%	-Not recommended to run on smoothed files (see Conn / ART NITRC post). 
%------------------------------------------------------------------------------------

% Select which files you want to run ART on: 
% RF_1 = spm_select('ExtFPList', fullfile(data_path),'^wra.*RightFoot_Run1\.nii$',1:178); 
% RF_2 = spm_select('ExtFPList', fullfile(data_path),'^wra.*RightFoot_Run2\.nii$',1:178); 
% LF_1 = spm_select('ExtFPList', fullfile(data_path),'^wra.*LeftFoot_Run1\.nii$',1:178); 
% LF_2 = spm_select('ExtFPList', fullfile(data_path),'^wra.*LeftFoot_Run2\.nii$',1:178); 

data = cellstr(spm_select('FPList', data_path, '^w.*'));

%Run ART
clear batch 
batch.filename=fullfile(data_path,'conn_ART.mat');
batch.Setup.isnew=1;
batch.Setup.nsubjects=1;
conn_batch(batch) %A workaround to create a new project before adding the rest. Otherwise it seems that Conn gets overwhelmed and won't work. 
%batch.Setup.functionals{1}{1}=RF_1;
%batch.Setup.functionals{1}{2}=RF_2;
%batch.Setup.functionals{1}{3}=LF_1;
%batch.Setup.functionals{1}{4}=LF_2;
batch.filename=fullfile(data_path,'conn_ART.mat');
batch.Setup.functionals{1}{1}=data
batch.Setup.preprocessing.art_thresholds(1)=5; %art_thresholds(1): threshold value for global-signal (z-value; default 5) 
batch.Setup.preprocessing.art_thresholds(2)=1; %art_thresholds(2): threshold value for subject-motion (mm; default .9) 
batch.Setup.preprocessing.art_thresholds(3)=1; %art_thresholds(3): global-signal threshold based on scan-to-scan changesin global-BOLD measure (default 1)  
batch.Setup.preprocessing.art_thresholds(4)=1; %art_thresholds(4): subject-motion threshold based on scan-to-scan changes in subject-motion measure (default 1) 
batch.Setup.preprocessing.art_thresholds(5)=1; %art_thresholds(5): subject-motion threhsold based on composite-movement measure (default 1) 


batch.Setup.preprocessing.steps={'functional_art'}; 
conn_batch(batch); %run the Conn batch 

end





