function LASAUULAATYDYYfMRIN19 = import_syllables(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LASAUULAATYDYYFMRIN19 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  LASAUULAATYDYYFMRIN19 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  LASAUULAATYDYYfMRIN19 = importfile("/Users/noeliamartinezmolina/Documents/Aphasia_project/tb-fMRI/results/behaviour/LASA_UULAATYDYY_fMRI_N19.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-May-2022 16:59:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["ID_BIDS", "ID", "Group", "UU_TY_syllable_sum_INT", "UU_TY_syllable_sum_syllables_errors_INT", "UU_TY_syllable_sum_percent_INT", "XX_minus_YY_syll_sum_perc_INT"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
LASAUULAATYDYYfMRIN19 = readtable(filename, opts);

end