function LASAquestionnairesCVATBIbehfMRIfixed = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LASAQUESTIONNAIRESCVATBIBEHFMRIFIXED = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  LASAQUESTIONNAIRESCVATBIBEHFMRIFIXED = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  LASAquestionnairesCVATBIbehfMRIfixed = importfile("/Users/noeliamartinezmolina/Documents/GitHub/tbfMRI_LASA_current_code/notebooks/behaviour/LASA_questionnaires_CVA_TBI_beh_fMRI_fixed.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Apr-2022 16:21:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["ID_num", "ID", "Time_since_injury_at_TP1", "pDemAge", "pDemGender", "pDemHand", "pDemHandComment", "pDemLanguage", "Group", "Communication_index_P_1", "Communication_index_P_2", "Communication_index_P_3", "Communication_index_P_21", "Communication_index_P_32", "Communication_index_INT", "Change_WAB_naming_repetition_21", "Change_WAB_naming_repetition_32", "Change_WAB_naming_repetition_intervention"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "pDemHandComment", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["pDemHandComment", "pDemLanguage"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ID", "TrimNonNumeric", true);
opts = setvaropts(opts, "ID", "ThousandsSeparator", ",");

% Import the data
LASAquestionnairesCVATBIbehfMRIfixed = readtable(filename, opts);

end